site_name: Telebof 
nav:
    - Introduction: index.md
    - Installation: installation.md
    - Handling Updates: handling-updates.md
    - Filters: filters.md
    - Using states: states.md
    - Advanced Features: advance.md
    - Error Handling: error_handling.md
    - Examples: 
      - Examples: examples.md
      - Keyboard Bot: examples/keyboard_bot.md
      - Inline Keyboard Bot: examples/inline_keyboard_bot.md
      - Inline Bot: examples/inline_bot.md
      - Payment Bot: examples/payment_bot.md
      - State Bot: examples/state_bot.md
      - Welcome Bot: examples/welcome_bot.md
      - Media Downloader: examples/media_downloader.md
      - Spring Boot Webhook Bot: examples/webhook_spring
     

copyright: Copyright &copy; 2025 Natanim
theme: 
  name: material
  palette: 
    - scheme: slate
  features:
    - navigation.top
    - content.code.copy
    - navigation.footer 
  icon: 
    repo: fontawesome/brands/github
      
repo_url: https://github.com/natanimn/telebof

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/natanimn/telebof
      name: Github
    - icon: fontawesome/brands/telegram 
      link: https://t.me/telebof
      name: Telegram
    - icon: fontawesome/brands/java 
      link: https://mvnrepository.com/artifact/io.github.natanimn/telebof


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences

